name: GCS to BQ to Spanner and MySQL via Composer

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decode SA key
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > /tmp/sa-key.json

      - name: Authenticate to GCP
        run: |
          gcloud auth activate-service-account \
            --key-file=/tmp/sa-key.json \
            --project=crested-acumen-495421-n0
          gcloud config set project crested-acumen-495421-n0
          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/sa-key.json" >> $GITHUB_ENV

      # STEP 1 - Upload all files to GCS
      - name: Step 1 - Upload files to GCS
        run: |
          gsutil cp Manu.txt             gs://lumibucket-1/Manu.txt
          gsutil cp scripts/schema.json  gs://lumibucket-1/scripts/schema.json
          gsutil cp scripts/transform.js gs://lumibucket-1/scripts/transform.js
          echo "Done - files uploaded to GCS"

      # STEP 2 - Upload DAG to Composer
      - name: Step 2 - Upload DAG to Composer
        run: |
          # Get the Composer DAGs bucket
          COMPOSER_BUCKET=$(gcloud composer environments describe manu-composer \
            --location=us-central1 \
            --project=crested-acumen-495421-n0 \
            --format="value(config.dagGcsPrefix)")
          
          echo "Composer DAGs bucket: $COMPOSER_BUCKET"
          
          # Upload the DAG file
          gsutil cp dags/manu_pipeline_dag.py $COMPOSER_BUCKET/manu_pipeline_dag.py
          echo "Done - DAG uploaded to Composer"

      # STEP 3 - Trigger the DAG
      - name: Step 3 - Trigger DAG in Composer
        run: |
          gcloud composer environments run manu-composer \
            --location=us-central1 \
            --project=crested-acumen-495421-n0 \
            dags trigger -- manu_pipeline
          echo "Done - DAG triggered!"